### ISSUE TITLE
GameGUI gets moved offscreen on clients, especially webgl

### ISSUE THREAD

**Issue by rcahoon** [Team766/2020Sim#14]
Started happening when we added a NetworkIdentity component to it. Probably to do with the fact that NetworkIdentity disables game objects until the server connection is established, and this interacts badly with initialization of the UI Canvas.

Seems to happen inconsistently. On some builds, the shift is very small so it doesn't matter, on others the GUI is completely offscreen

**Comment by rcahoon** [comment]
This post was very helpful in solving this issue: https://forum.unity.com/threads/understanding-canvas-scaler-screen-match-mode-and-reference-resolution.524194/

**Comment by Samir-Rashid** [comment]
I am still having some issues trying to display the GUI. From the location and layers it doesn't seem to be moving off screen for me, but when I play or build to WebGL or MacOS desktop app the Canvas seems to disappear.
I will try and look into this. The only reason I can think of is that I'm running the latest stable of Unity 2019.4.12f1 rather than 2019.4.2f1.

**Comment by Samir-Rashid** [comment]
🤔 I randomly found a huge UI
![gif](https://user-images.githubusercontent.com/35205346/95544705-c6416280-09b0-11eb-87ce-b400f725b805.gif)

**Comment by Samir-Rashid** [comment]
oops. I think this was completely my fault 😅 
For me when the program runs starting in bird's eye view the GUI gets disabled. I would guess this is on purpose. If I just re-enable the GUi everything works fine.
